groups:
  - name: alert_rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: 'Instance [{{ $labels.instance }}] down'
          description: '[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 10 seconds.'
      # - alert: DiskSpaceFree
      #   expr: node_filesystem_free_percent <= 10
      #   labels:
      #     severity: warning
      #   annotations:
      #     summary: 'Instance [{{ $labels.instance }}] has 10% or less Free disk space'
      #     description: '[{{ $labels.instance }}] has only {{ $value }}% or less free.'
